version: "3.1"

services:
  jupyterhub:
    container_name: jhub
    image: jupyterhub-nbgrader
    build: .
    ports:
      - 443:443
    env_file:
      - ./.env

    volumes:
      # Mount python library
      - ./lti_synchronization:/srv/jupyterhub/lti_synchronization

      # Mount folders to copy backups to
      - ./misc/backup:/backup
      - ./shell/backup.sh:/srv/jupyterhub/backup.sh

      # Mount SSL certificate
      - /root/certificates/jhub-dev_cos_ncsu_edu_cert.cer:/srv/jupyterhub/ssc_jhub.crt:ro
      - /root/certificates/jhub-dev.cos.ncsu.edu.key:/srv/jupyterhub/ssc_jhub.key:ro

      # Mount global nbgrader configuration
      - ./jupyterhub/nbgrader_configuration/nbgrader_global_config.py:/etc/jupyter/nbgrader_config.py

    command: jupyterhub &>> /srv/jupyterhub/jupyterhub.log
