version: "3.1"

services:
  jupyterhub:
    container_name: jhub
    image: jupyterhub-nbgrader
    build: .
    ports:
      - 443:443
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./backup:/backup
      - ./backup.sh:/srv/jupyterhub/backup.sh
      #  jhub-dev_cos_ncsu_edu_cert.cer  jhub-dev.cos.ncsu.edu.csr  jhub-dev.cos.ncsu.edu.key
      - /root/certificates/jhub-dev_cos_ncsu_edu_cert.cer:/srv/jupyterhub/ssc_jhub.crt:ro
      - /root/certificates/jhub-dev.cos.ncsu.edu.key:/srv/jupyterhub/ssc_jhub.key:ro
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    command: jupyterhub &>> /srv/jupyterhub/jupyterhub.log

volumes:
  backup:
