version: "3.1"

services:
  jupyterhub:
    container_name: jhub
    image: jupyterhub-nbgrader
    build: ./jupyterhub
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      - ./moodle_importer:/srv/jupyterhub/moodle_importer

      - ./misc/backup:/backup
      - ./shell/backup.sh:/srv/jupyterhub/backup.sh

      - /root/certificates/jhub-dev_cos_ncsu_edu_cert.cer:/srv/jupyterhub/ssc_jhub.crt:ro
      - /root/certificates/jhub-dev.cos.ncsu.edu.key:/srv/jupyterhub/ssc_jhub.key:ro

#       - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupyterhub/nbgrader_configuration/nbgrader_global_config.py:/etc/jupyter/nbgrader_config.py

      # Update nbgrader to ignore SSL certificate.
      - ./jupyterhub/nbgrader/handlers.py:/usr/local/lib/python3.8/dist-packages/nbgrader/server_extensions/course_list/handlers.py

      # Update LTI authenticator with patched verion
      - ./jupyterhub/ltiauthenticator/:/usr/local/lib/python3.8/dist-packages/ltiauthenticator/

    command: jupyterhub &>> /srv/jupyterhub/jupyterhub.log
