version: "3.1"

services:
  jupyterhub:
    container_name: jhub
    image: jupyterhub-nbgrader
    build: .
    ports:
      - 443:443
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./backup.sh:/srv/jupyterhub/backup.sh
      - ./cert/ssc_jhub.key:/srv/jupyterhub/ssc_jhub.key:ro
      - ./cert/ssc_jhub.crt:/srv/jupyterhub/ssc_jhub.crt:ro
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    command: jupyterhub &>> /srv/jupyterhub/jupyterhub.log
