version: "3.1"

services:
  jupyterhub:
    container_name: hub
    build: .
    ports:
      - 443:443
    volumes:
      - /etc/ssl/private/ssc_jhub.key:/etc/ssl/private/ssc_jhub.key
      - /etc/ssl/certs/ssc_jhub.crt:/etc/ssl/certs/ssc_jhub.crt
      - ./:/srv/JupyterHub
