class Config(object):
    '''
    Storage for the configuration presets.
    '''

    home_config: str = '''
c = get_config()

c.CourseDirectory.root = '/home/{grader}/{course_id}'
c.CourseDirectory.db_url = '{db_url}'
c.CourseDirectory.course_id = '{course_id}'
'''

    course_config: str = '''
c = get_config()

c.CourseDirectory.course_id = '{course_id}'
'''

    users: str = '''
c.LTIAuthenticator.allowed_users = {whitelist}

c.Authenticator.admin_users = {admin_users}

c.JupyterHub.load_groups = {groups}

c.JupyterHub.services = {services}

c.JupyterHub.api_tokens = {tokens}
'''

    template_warning: str = '''"""
DO NOT EDIT THIS FILE!

Since it was auto-generated by the lti_synchronization
Script. Rather, consider editing template file to make changes
consistent. You can find it's location in
IntegrationManager.path.in_file attribute
"""
'''
