"""
DO NOT EDIT THIS FILE!

Since it was auto-generated by the lti_synchronization
Script. Rather, consider editing template file to make changes
consistent. You can find it's location in
IntegrationManager.path.in_file attribute
"""

import os
from unittest.mock import MagicMock

from jupyterhub.spawner import LocalProcessSpawner

# mocking c variable in dev environment
if os.getenv('DEBUG', 'True') == 'True':
    c = MagicMock()

# ---------------
# IP
# ---------------

c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.port = 443

c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': 'frame-ancestors \'self\' *'
    },
    'cookie_options': {
        'SameSite': 'None',
        'Secure': True
    },
}

c.JupyterHub.allow_root = True
c.JupyterHub.allow_origin = '*'

# ---------------
# SSL
# ---------------

c.JupyterHub.ssl_cert = os.getenv('SSL_CERT_PATH', None)
c.JupyterHub.ssl_key = os.getenv('SSL_KEY_PATH', None)

# ---------------
# DIRECTORY
# ---------------

MODULE_NAME: str = 'lti_synchronization.moodle'

# ---------------
# AUTHENTICAION
# ---------------

c.JupyterHub.authenticator_class = f'{MODULE_NAME}.authenticators.authenticator.LTI13Authenticator'

c.LTI13Authenticator.endpoint = os.environ.get(
    'LTI13_ENDPOINT',
    'https://illumidesk.instructure.com/api/lti/security/jwks')

c.LTI13Authenticator.client_id = os.environ.get('LTI13_CLIENT_ID')

c.LTI13Authenticator.authorize_url = os.environ.get(
    'LTI13_AUTHORIZE_URL',
    'https://illumidesk.instructure.com/api/lti/authorize_redirect')

c.LTI13Authenticator.token_url = os.environ.get(
    'LTI13_TOKEN_URL', 'https://illumidesk.instructure.com/login/oauth2/token')

c.JupyterHub.extra_handlers = [
    (r'/lti13/config$', f'{MODULE_NAME}.handlers.LTI13ConfigHandler'),
    (r'/lti13/jwks$', f'{MODULE_NAME}.lti13.handlers.LTI13JWKSHandler'),
    (r'/submit-grades/(?P<course_id>\w+)/(?P<assignment_name>\w+)',
     f'{MODULE_NAME}.grades.SendGradesHandler'),
]

c.Authenticator.enable_auth_state = True

c.LocalAuthenticator.auto_login = True

c.LocalAuthenticator.create_system_users = True

# ---------------
# SPAWNER
# ---------------

c.JupyterHub.spawner_class = LocalProcessSpawner

c.Spawner.args = [
    '--debug',
]

c.LocalProcessSpawner.shell_cmd = ['bash', '-l', '-c']


def pre_spawn_hook(spawner) -> None:

    spawner.log.warning(f'Spawning {spawner.user.name}')


def bind_auth_state(spawner, auth_state: dict) -> None:

    spawner.log.info('Bind auth state to a spawner.')

    spawner.userdata = auth_state


c.JupyterHub.spawner_class = LocalProcessSpawner

c.Spawner.auth_state_hook = bind_auth_state

c.Spawner.pre_spawn_hook = pre_spawn_hook

c.Spawner.args = ['--allow-root']

# ---------------
# USERS
# ---------------

c.JupyterHub.admin_access = True

c.LTIAuthenticator.allowed_users = {
    'grader-first_course', 'grader-your_school', 'api_user', 'admin'
}

c.Authenticator.admin_users = {
    'admin', 'grader-first_course', 'api_user', 'grader-Your School'
}

c.JupyterHub.load_groups = {
    'formgrade-your_school': ['grader-your_school'],
    'nbgrader-your_school': [],
    'formgrade-Your School': ['api_user'],
    'formgrade-first_course': ['grader-first_course', 'admin'],
    'nbgrader-first_course': []
}

c.JupyterHub.services = [{
    'name':
    'your_school',
    'admin':
    True,
    'url':
    'http://127.0.0.1:9000',
    'command': [
        'jupyterhub-singleuser', '--group=formgrade-your_school', '--debug',
        '--allow-root'
    ],
    'user':
    'grader-your_school',
    'cwd':
    '/home/grader-your_school',
    'api_token':
    '7031d88c4e2b0f1dafa0a78bda263c0413cf94f6354a1779b174026a3e0f7ce3',
    'environment': {
        'JUPYTERHUB_SERVICE_USER': 'grader-your_school'
    }
}, {
    'name':
    'first_course',
    'admin':
    True,
    'url':
    'http://127.0.0.1:9001',
    'command': [
        'jupyterhub-singleuser', '--group=formgrade-first_course', '--debug',
        '--allow-root'
    ],
    'user':
    'grader-first_course',
    'cwd':
    '/home/grader-first_course',
    'api_token':
    '4fb54074520b0d286e7164d1d64ca0d6084575fbef0ba8e86d217cf570c44886',
    'environment': {
        'JUPYTERHUB_SERVICE_USER': 'grader-first_course'
    }
}]

c.JupyterHub.api_tokens = {
    '7031d88c4e2b0f1dafa0a78bda263c0413cf94f6354a1779b174026a3e0f7ce3':
    'grader-your_school',
    '4fb54074520b0d286e7164d1d64ca0d6084575fbef0ba8e86d217cf570c44886':
    'grader-first_course'
}
